plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory:
    now:
      description: ServiceNow Inventory Plugin
      name: now
      version_added: '2.10'
  lookup: {}
  module:
    snow_record:
      description: Manage records in ServiceNow
      name: snow_record
      namespace: ''
      version_added: null
    snow_record_find:
      description: Search for multiple records from ServiceNow
      name: snow_record_find
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.0.4
