---
- hosts: localhost
  gather_facts: no

  tasks:
    - set_fact:
        docs: "{{ lookup('file', '../plugins/inventory/now.py') | regex_search(\"(?<=DOCUMENTATION\\s=\\s''')((.|\\n)*?)(?=''')\") | from_yaml}}"
        examples: "{{ lookup('file', '../plugins/inventory/now.py') | regex_search(\"(?<=EXAMPLES\\s=\\s''')((.|\\n)*?)(?=''')\") }}"

    - template:
        src: ./templates/inventory.md.j2
        dest: ./inventory.md